# Generated by Django 5.2.3 on 2025-07-01 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('instance_type', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('restart_attempts', models.IntegerField(default=0)),
                ('auto_restart_enabled', models.BooleanField(default=False)),
                ('last_restart_attempt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일 주소')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자 이름')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='이름')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='성')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 상태')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 상태')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'server_manager_user',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('rejected', '거부됨'), ('canceled', '취소됨'), ('completed', '완료됨')], default='pending', max_length=20, verbose_name='상태')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='사용 목적')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='관리자 코멘트')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='server_manager.instance', verbose_name='인스턴스')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('scheduled_end', models.DateTimeField(null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_manager.instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
