# Generated by Django 5.2.3 on 2025-07-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
